#!/bin/bash
sed 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf > /tmp/pac.conf
sudo pacman -U --noconfirm \
  --config /tmp/pac.conf \
  http://192.168.122.1:8080/leaf-kde-theme-1.0.0-4-any.pkg.tar.zst \
  http://192.168.122.1:8080/velox-kickoff-6.7.1-1-any.pkg.tar.zst
rm /tmp/pac.conf
